name: weather_service
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  flutter_animate: ^4.2.0+1
  google_fonts: ^5.1.0
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/weather_icons/big/
    - assets/weather_icons/small/
    - assets/svg_icons/
